// ------------------------------------------------------------------------------
//  <auto-generated>
//    This code was auto-generated by 'com.unity.microsoft.gdk.tools:GdkPlatformSettingsGenerator', version 
////    Changes to this file may cause incorrect behavior and will be lost when
//    regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace ELECTRIS
{
public static class GdkPlatformSettings
{
    // A Microsoft Game Config (MGC) asset has not been configured for this platform (see GDK Settings).
}
}
