
#include "GPUICrowdSkinning.cginc"

#ifndef GPUICA_SG_INCLUDED
#define GPUICA_SG_INCLUDED

void gpuiAnimate_float(float4 GPUI_BONE_INDEX, float4 GPUI_BONE_WEIGHT, float3 GPUI_VERTEX, float3 GPUI_NORMAL, float3 GPUI_TANGENT, out float3 OUT_GPUI_VERTEX, out float3 OUT_GPUI_NORMAL, out float3 OUT_GPUI_TANGENT)
{
    gpuiCASkinning(GPUI_BONE_INDEX, GPUI_BONE_WEIGHT, GPUI_VERTEX, GPUI_NORMAL, GPUI_TANGENT, OUT_GPUI_VERTEX, OUT_GPUI_NORMAL, OUT_GPUI_TANGENT);
}

#endif