blank_issues_enabled: false
contact_links:
  - name: ⛑️ Official Discord Server
    url: https://discord.gg/TgtCGKxbZr
    about: Issues are not for support. If you need it - join the Discord server.
